export const HANDLE_INPUT_CHANGE = 'handle_input_change'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TODO_ITEM = 'delete_todo_item'
export const INIT_TODO_LIST = 'init_todo_list'
export const GET_TODO_LIST = 'get_todo_list'